id: P001702
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19960
  title: གཏོར་མ་བརྒྱ་རྩའི་རྣམ་པར་བཤད་པ་དང་དཀར་ཆ་བཞིའི་རྣམ་བཤད།
  author: ''
  volumes:
    cb518bc981764d1ca4a619dd96630c6e:
      image_group_id: I8LS19962
      title: ''
      volume_number: 1
      total_pages: 80
