id: P001702
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:15:33.411139
source_metadata:
  id: bdr:W8LS19960
  title: གཏོར་མ་བརྒྱ་རྩའི་རྣམ་པར་བཤད་པ་དང་དཀར་ཆ་བཞིའི་རྣམ་བཤད།
  author: ''
  volumes:
    cb518bc981764d1ca4a619dd96630c6e:
      image_group_id: I8LS19962
      title: ''
      volume_number: 1
      total_pages: 80
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
